version: '3.6'
services:
  jupyter:
    build: .
    ports:
      - "5000:5000"
  sql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    entrypoint: /mssql/entrypoint.sh
    command: /opt/mssql/bin/sqlservr
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql:/mssql
